from __future__ import annotations

from typing import Any

from libshared.agent_contracts import agent_contract


INDEPENDENT_INPUT_SCHEMAS: dict[str, list[dict[str, Any]]] = {
    "orchestrator": [{"name": "prompt", "label": "任务目标与交付要求", "type": "textarea", "required": True, "placeholder": "说明产品、平台、目标受众、参考素材和期望交付。"}],
    "collector": [
        {"name": "target_type", "label": "采集方式", "type": "select", "required": True, "options": [{"value": "keyword", "label": "关键词"}, {"value": "account", "label": "TikTok 账号"}, {"value": "hashtag", "label": "话题标签"}, {"value": "trending", "label": "热门视频"}]},
        {"name": "target", "label": "采集目标", "type": "text", "required": False, "placeholder": "输入关键词、账号主页或话题；热门视频可留空。"},
        {"name": "limit", "label": "候选数量", "type": "number", "required": True, "min": 1, "max": 20, "value": 6},
        {"name": "persist", "label": "下载并存入素材库", "type": "checkbox", "value": True},
    ],
    "analysis": [{"name": "source_text", "label": "视频转写、素材说明或链接", "type": "textarea", "required": True, "placeholder": "粘贴转写、视频内容说明或参考链接，Agent 将拆解结构、节奏和镜头。"}],
    "research": [{"name": "source_text", "label": "研究样本与背景", "type": "textarea", "required": True, "placeholder": "输入竞品转写、市场观察、目标受众或已有分析结论。"}],
    "strategy": [
        {"name": "product_id", "label": "产品名称或策略主题", "type": "text", "required": True, "placeholder": "例如便携恒温杯、折叠雨伞或品牌故事"},
        {"name": "source_text", "label": "产品事实与传播目标", "type": "textarea", "required": True, "placeholder": "输入已确认卖点、目标用户、平台和希望达成的内容目标。"},
    ],
    "script": [
        {"name": "product_id", "label": "产品名称或创作主题", "type": "text", "required": True, "placeholder": "例如便携恒温杯、婴儿背带或品牌故事"},
        {"name": "prompt", "label": "脚本创作需求", "type": "textarea", "required": True, "placeholder": "说明产品事实、受众、场景、剧情方向、平台和时长。"},
    ],
    "script_breakdown": [
        {"name": "product_id", "label": "产品名称或创作主题", "type": "text", "required": True, "placeholder": "用于识别产品事实和安全边界"},
        {"name": "source_text", "label": "待拆解脚本", "type": "textarea", "required": True, "placeholder": "粘贴完整脚本，生成逐段意图、画面、动作和连续性要求。"},
    ],
    "storyboard": [
        {"name": "product_id", "label": "产品名称或创作主题", "type": "text", "required": True, "placeholder": "用于匹配产品事实与视觉约束"},
        {"name": "prompt", "label": "脚本或分镜需求", "type": "textarea", "required": True, "placeholder": "输入脚本，或明确场景、人物、动作、镜头运动和视觉风格。"},
    ],
    "asset": [{"name": "prompt", "label": "镜头素材需求", "type": "textarea", "required": True, "placeholder": "说明需要匹配的产品、动作、构图和关键帧要求。"}],
    "production": [{"name": "prompt", "label": "单镜视频 Prompt", "type": "textarea", "required": True, "placeholder": "描述单个 6 秒镜头的场景、人物、动作、产品状态、机位和光线。"}],
    "review": [
        {"name": "product_id", "label": "产品名称或审核主题", "type": "text", "required": True, "placeholder": "用于加载对应产品事实；未入库产品请在正文写明事实"},
        {"name": "source_text", "label": "待审核脚本或内容", "type": "textarea", "required": True, "placeholder": "粘贴脚本、分镜说明或广告文案，检查产品事实、合规和表达风险。"},
    ],
    "feedback": [{"name": "source_text", "label": "复盘反馈", "type": "textarea", "required": True, "placeholder": "记录问题、原因、修改建议和希望沉淀的规则。"}],
}


AGENT_CAPABILITIES: tuple[dict[str, Any], ...] = (
    {
        "id": "orchestrator",
        "number": "01",
        "name": "Orchestrator Agent",
        "role": "总控编排",
        "status": "deployed",
        "inputs": ["目标", "产品", "参考素材"],
        "outputs": ["任务路由", "检查点", "结果汇总"],
        "tools": ["queue", "checkpoint", "gate"],
        "human_gate": "异常处理与闸门放行",
        "independent_action": "orchestrator",
        "independent_inputs": ["任务目标", "产品", "参考素材与交付要求"],
    },
    {
        "id": "collector",
        "number": "02C",
        "name": "Collector Agent",
        "role": "素材采集与入库",
        "status": "partial",
        "inputs": ["关键词", "账号", "话题", "视频链接"],
        "outputs": ["tiktok_capture", "material_meta"],
        "tools": ["TikTokApi", "yt-dlp", "oEmbed", "manual import"],
        "human_gate": "采集范围、来源合规与入库筛选",
        "independent_action": "collector",
        "independent_inputs": ["关键词、账号、话题或视频链接"],
        "gap": "自动 ASR、镜头边界检测和稳定会话仍需持续增强",
    },
    {
        "id": "analysis",
        "number": "02A",
        "name": "Analysis Agent",
        "role": "素材结构分析",
        "status": "deployed",
        "inputs": ["视频转写", "素材说明", "参考链接"],
        "outputs": ["analysis_report"],
        "tools": ["doubao_analyze", "manual transcript"],
        "human_gate": "确认分析范围与参考边界",
        "independent_action": "analysis",
        "independent_inputs": ["转写文本、素材说明或参考链接"],
    },
    {
        "id": "research",
        "number": "02",
        "name": "Research Agent",
        "role": "研究洞察",
        "status": "deployed",
        "inputs": ["TikTok 元数据", "转写文本", "分析报告"],
        "outputs": ["research_brief"],
        "tools": ["tiktok_oembed", "doubao", "manual transcript"],
        "human_gate": "确认研究范围与竞品样本",
        "independent_action": "research",
        "independent_inputs": ["关键词/账号/链接", "可选转写"],
    },
    {
        "id": "strategy",
        "number": "03",
        "name": "Strategy Agent",
        "role": "内容策略",
        "status": "deployed",
        "inputs": ["research_brief", "产品事实"],
        "outputs": ["strategy_brief"],
        "tools": ["doubao", "product guardrails"],
        "human_gate": "策略方向与卖点选择",
        "independent_action": "strategy",
        "independent_inputs": ["研究文本", "产品事实"],
    },
    {
        "id": "script",
        "number": "04",
        "name": "Script Agent",
        "role": "脚本创作与拆解",
        "status": "deployed",
        "inputs": ["strategy_brief", "script_copy"],
        "outputs": ["script_copy", "script_breakdown"],
        "tools": ["doubao", "compliance guardrails"],
        "human_gate": "逐段修改脚本与拆解",
        "independent_action": "script,script_breakdown",
        "independent_inputs": ["用户需求/产品/参考文本"],
    },
    {
        "id": "storyboard",
        "number": "05",
        "name": "Storyboard Agent",
        "role": "分镜策划",
        "status": "deployed",
        "inputs": ["script_copy"],
        "outputs": ["shot_plan"],
        "tools": ["doubao_shotplan"],
        "human_gate": "逐镜确认与镜头调整",
        "independent_action": "storyboard",
        "independent_inputs": ["脚本或自定义 Prompt"],
    },
    {
        "id": "asset",
        "number": "06",
        "name": "Asset Agent",
        "role": "素材处理",
        "status": "partial",
        "inputs": ["shot_plan", "产品素材库"],
        "outputs": ["asset_manifest", "hero_frames"],
        "tools": ["product library", "hero_frame"],
        "human_gate": "产品身份锚点与关键帧确认",
        "independent_action": "asset",
        "independent_inputs": ["镜头需求或脚本", "产品素材"],
        "gap": "缺少场景式 contact sheet 与素材去重评分",
    },
    {
        "id": "production",
        "number": "07",
        "name": "Production Agent",
        "role": "视频生成与合成",
        "status": "deployed",
        "inputs": ["shot_plan", "asset_manifest"],
        "outputs": ["shot_report", "render_report"],
        "tools": ["Seedance", "FFmpeg"],
        "human_gate": "逐镜预览、重生成与合成",
        "independent_action": "production",
        "independent_inputs": ["单镜 Prompt", "产品素材"],
    },
    {
        "id": "review",
        "number": "08",
        "name": "Review Agent",
        "role": "审核质检",
        "status": "partial",
        "inputs": ["脚本", "分镜", "视频"],
        "outputs": ["review_report", "qa_report"],
        "tools": ["doubao_review", "ffprobe", "rule checks"],
        "human_gate": "人工终审与放行",
        "independent_action": "review",
        "independent_inputs": ["脚本文本或内容需求"],
        "gap": "人物一致性与产品结构视觉检查仍需人工",
    },
    {
        "id": "feedback",
        "number": "09",
        "name": "Feedback Agent",
        "role": "反馈学习",
        "status": "partial",
        "inputs": ["人工反馈", "发布表现"],
        "outputs": ["feedback record"],
        "tools": ["feedback library"],
        "human_gate": "采纳反馈与模板升级",
        "independent_action": "feedback",
        "independent_inputs": ["人工反馈、复盘结论或优化要求"],
        "gap": "尚未接入平台表现数据与自动策略更新",
    },
)


def capability_map() -> dict[str, Any]:
    agents = []
    for item in AGENT_CAPABILITIES:
        enriched = dict(item)
        enriched.update(agent_contract(str(item["id"])))
        agents.append(enriched)
    return {
        "version": "1.0",
        "agents": agents,
        "input_schemas": INDEPENDENT_INPUT_SCHEMAS,
        "summary": {
            "total": len(agents),
            "deployed": sum(item["status"] == "deployed" for item in agents),
            "partial": sum(item["status"] == "partial" for item in agents),
            "missing": sum(item["status"] == "missing" for item in agents),
        },
        "collector": next(item for item in agents if item["id"] == "collector"),
    }
