from __future__ import annotations

from typing import Any


AGENT_CAPABILITIES: tuple[dict[str, Any], ...] = (
    {
        "id": "orchestrator",
        "number": "01",
        "name": "Orchestrator Agent",
        "role": "总控编排",
        "status": "deployed",
        "inputs": ["目标", "产品", "参考素材"],
        "outputs": ["任务路由", "检查点", "结果汇总"],
        "tools": ["queue", "checkpoint", "gate"],
        "human_gate": "异常处理与闸门放行",
        "independent_action": None,
    },
    {
        "id": "research",
        "number": "02",
        "name": "Research Agent",
        "role": "研究洞察",
        "status": "deployed",
        "inputs": ["TikTok 元数据", "转写文本", "分析报告"],
        "outputs": ["research_brief"],
        "tools": ["tiktok_oembed", "doubao", "manual transcript"],
        "human_gate": "确认研究范围与竞品样本",
        "independent_action": "research",
    },
    {
        "id": "strategy",
        "number": "03",
        "name": "Strategy Agent",
        "role": "内容策略",
        "status": "deployed",
        "inputs": ["research_brief", "产品事实"],
        "outputs": ["strategy_brief"],
        "tools": ["doubao", "product guardrails"],
        "human_gate": "策略方向与卖点选择",
        "independent_action": "strategy",
    },
    {
        "id": "script",
        "number": "04",
        "name": "Script Agent",
        "role": "脚本创作与拆解",
        "status": "deployed",
        "inputs": ["strategy_brief", "script_copy"],
        "outputs": ["script_copy", "script_breakdown"],
        "tools": ["doubao", "compliance guardrails"],
        "human_gate": "逐段修改脚本与拆解",
        "independent_action": "script_breakdown",
    },
    {
        "id": "storyboard",
        "number": "05",
        "name": "Storyboard Agent",
        "role": "分镜策划",
        "status": "deployed",
        "inputs": ["script_copy"],
        "outputs": ["shot_plan"],
        "tools": ["doubao_shotplan"],
        "human_gate": "逐镜确认与镜头调整",
        "independent_action": None,
    },
    {
        "id": "asset",
        "number": "06",
        "name": "Asset Agent",
        "role": "素材处理",
        "status": "partial",
        "inputs": ["shot_plan", "产品素材库"],
        "outputs": ["asset_manifest", "hero_frames"],
        "tools": ["product library", "hero_frame"],
        "human_gate": "产品身份锚点与关键帧确认",
        "independent_action": None,
        "gap": "缺少场景式 contact sheet 与素材去重评分",
    },
    {
        "id": "production",
        "number": "07",
        "name": "Production Agent",
        "role": "视频生成与合成",
        "status": "deployed",
        "inputs": ["shot_plan", "asset_manifest"],
        "outputs": ["shot_report", "render_report"],
        "tools": ["Seedance", "FFmpeg"],
        "human_gate": "逐镜预览、重生成与合成",
        "independent_action": None,
    },
    {
        "id": "review",
        "number": "08",
        "name": "Review Agent",
        "role": "审核质检",
        "status": "partial",
        "inputs": ["脚本", "分镜", "视频"],
        "outputs": ["review_report", "qa_report"],
        "tools": ["doubao_review", "ffprobe", "rule checks"],
        "human_gate": "人工终审与放行",
        "independent_action": None,
        "gap": "人物一致性与产品结构视觉检查仍需人工",
    },
    {
        "id": "feedback",
        "number": "09",
        "name": "Feedback Agent",
        "role": "反馈学习",
        "status": "partial",
        "inputs": ["人工反馈", "发布表现"],
        "outputs": ["feedback record"],
        "tools": ["feedback library"],
        "human_gate": "采纳反馈与模板升级",
        "independent_action": None,
        "gap": "尚未接入平台表现数据与自动策略更新",
    },
)


def capability_map() -> dict[str, Any]:
    agents = [dict(item) for item in AGENT_CAPABILITIES]
    return {
        "version": "1.0",
        "agents": agents,
        "summary": {
            "total": len(agents),
            "deployed": sum(item["status"] == "deployed" for item in agents),
            "partial": sum(item["status"] == "partial" for item in agents),
            "missing": sum(item["status"] == "missing" for item in agents),
        },
        "collector": {
            "status": "partial",
            "available": ["TikTok oEmbed metadata", "manual URL intake", "manual transcript intake"],
            "missing": ["authorized video download", "automatic ASR", "frame sampling"],
        },
    }
